# Generated by Django 4.2.1 on 2023-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_bankmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='acnum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
