# Generated by Django 4.2.1 on 2023-07-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_newmodel_addamount_uid_withdrawamount_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newmodel',
            new_name='newmodels',
        ),
    ]
