# Generated by Django 4.2.1 on 2023-07-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_alter_newmodels_content_alter_newmodels_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=2000)),
                ('date', models.DateField()),
            ],
        ),
    ]
